spring:
  datasource:
    url: jdbc:h2:file:~/dev/env/db/demo;USER=sa;PASSWORD=password;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.orm.jdbc.bind: TRACE
    sql: DEBUG

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
